### ISSUE TITLE
missing "\" at the end of "|"

### ISSUE THREAD

**Issue by haifengkao** [fastred/Optimizing-Swift-Build-Times#4] opened 2017-11-09 06:38 UTC
```
xcodebuild -destination 'platform=iOS Simulator,name=iPhone 8' \
  -sdk iphonesimulator -project YourProject.xcodeproj \
  -scheme Chuck -configuration Debug \
  clean build \
  OTHER_SWIFT_FLAGS="-driver-time-compilation \
    -Xfrontend -debug-time-function-bodies \
    -Xfrontend -debug-time-compilation" |  <- should have "\" here?
tee profile.log
```

**Comment by fastred** [comment] 2017-11-09 09:39
It shouldn't be needed after a pipe operator. I tested this under Bash and zsh. What shell do you use?

**Comment by haifengkao** [comment] 2017-11-09 09:52
without `\`, it will hang indefinitely
![2017-11-09 5 49 11](https://user-images.githubusercontent.com/4080524/32599093-69845c7c-c576-11e7-9af0-7582210805c7.png)

my zsh:
zsh 5.3.1 (x86_64-apple-darwin17.0.0)

**Comment by haifengkao** [comment] 2017-11-09 09:53
with `\`
![2017-11-09 5 52 39](https://user-images.githubusercontent.com/4080524/32599215-d845aee0-c576-11e7-960a-dc4451abe379.png)

**Comment by fastred** [comment] 2017-11-11 10:29
I'm somehow not able to reproduce this.

Does this not return the correct result for you too?

```sh
echo "1\n2" |
wc
```

**Comment by yakovlevmaksym** [comment] 2017-11-12 09:50
I have the same issue. Should use '\' after '|'. 

Shell: fish.

**Comment by fastred** [comment] 2017-11-13 10:08
Thanks for reporting! Should be fixed now on `master`.

**Closed as completed** 2017-11-13 10:07 UTC
